<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * LRP API Endpoints
 * - POST /wp-json/lrp/v1/event   => create event
 * - GET  /wp-json/lrp/v1/event   => get events / customer summary
 * - PUT  /wp-json/lrp/v1/event   => update event by transaction or id
 *
 * Paste this file into your plugin and ensure it is included on every request (not admin-only).
 */

class LRP_API_Endpoints {

    public function __construct() {
    add_action( 'rest_api_init', array( $this, 'register_rest_routes' ) );
    add_action( 'rest_api_init', array( $this, 'lrp_register_debug_route' ) );
}


    public function register_rest_routes() {
        register_rest_route( 'lrp/v1', '/event', [
            [
                'methods' => 'POST',
                'callback' => [ $this, 'lrp_rest_create_event' ],
                'permission_callback' => [ $this, 'lrp_rest_permission_check' ],
            ],
            [
                'methods' => 'GET',
                'callback' => [ $this, 'lrp_rest_get_event' ],
                'permission_callback' => [ $this, 'lrp_rest_permission_check' ],
            ],
            [
                'methods' => 'PUT',
                'callback' => [ $this, 'lrp_rest_update_event' ],
                'permission_callback' => [ $this, 'lrp_rest_permission_check' ],
            ],
        ] );
    }

    /**
     * Permission: allow WP user with manage_options OR header LRP-API-Key matching option
     */
    public function lrp_rest_permission_check( $request ) {
        // WP user with capability
        if ( is_user_logged_in() && current_user_can( 'manage_options' ) ) {
            return true;
        }

        // header-based API key (try different capitalizations)
        $key = '';
        if ( function_exists('getallheaders') ) {
            $headers = getallheaders();
            if ( ! empty( $headers['LRP-API-Key'] ) ) $key = $headers['LRP-API-Key'];
            elseif ( ! empty( $headers['Lrp-Api-Key'] ) ) $key = $headers['Lrp-Api-Key'];
        }
        if ( empty( $key ) && ! empty( $_SERVER['HTTP_LRP_API_KEY'] ) ) {
            $key = sanitize_text_field( $_SERVER['HTTP_LRP_API_KEY'] );
        }

        $expected = get_option( 'lrp_api_key', '' );
        if ( $expected && $key && hash_equals( (string) $expected, (string) $key ) ) {
            return true;
        }

        return new WP_Error( 'rest_forbidden', __( 'You are not authorized to use this API.', 'NetScore Loyalty Rewards' ), array( 'status' => 401 ) );
    }

    /**
 * POST - create event (single object or array of objects)
 */
public function lrp_rest_create_event( WP_REST_Request $request ) {
    global $wpdb;
    $body = $request->get_json_params();

    if ( empty( $body ) ) {
        return new WP_Error( 'invalid_payload', 'Invalid JSON payload', array( 'status' => 400 ) );
    }

    // Normalize payload to array of items (support single object or array)
    $items = is_array( $body ) && array_keys( $body ) === range(0, count($body)-1) ? $body : array( $body );

    $results = array();
    foreach ( $items as $idx => $item ) {
        // validate individual item
        if ( ! is_array( $item ) ) {
            $results[] = array( 'success' => false, 'error' => 'invalid_item', 'message' => 'Each item must be an object', 'index' => $idx );
            continue;
        }

        // require customerEmail
        $customerEmail = isset( $item['customerEmail'] ) ? sanitize_email( $item['customerEmail'] ) : '';
        if ( empty( $customerEmail ) ) {
            $results[] = array( 'success' => false, 'error' => 'missing_customer_email', 'message' => 'customerEmail is required in JSON body', 'index' => $idx );
            continue;
        }

        // normalize fields (per-item)
        $eventDate           = isset( $item['eventDate'] ) ? sanitize_text_field( $item['eventDate'] ) : gmdate( 'Y-m-d' );
        $eventid             = isset( $item['eventid'] ) ? intval( $item['eventid'] ) : null;
        $customerId          = isset( $item['customerId'] ) ? intval( $item['customerId'] ) : 0;
        $mainCustomerID      = isset( $item['mainCustomerID'] ) ? intval( $item['mainCustomerID'] ) : $customerId;
        $positive_negative   = isset( $item['positive_negative'] ) ? sanitize_text_field( $item['positive_negative'] ) : 'positive';
        $pointsEarned        = isset( $item['pointsEarned'] ) ? floatval( $item['pointsEarned'] ) : 0.0;
        $pointsRedeemed      = isset( $item['pointsRedeemed'] ) ? floatval( $item['pointsRedeemed'] ) : 0.0;
        // transaction: use provided reference, otherwise null (no autogenerated random)
        $transaction_id      = isset( $item['transaction'] ) && $item['transaction'] !== '' ? sanitize_text_field( $item['transaction'] ) : null;
        $amount              = isset( $item['amount'] ) ? floatval( $item['amount'] ) : 0.0;
        $giftCode            = isset( $item['giftCode'] ) ? sanitize_text_field( $item['giftCode'] ) : null;
        $receiverEmail       = isset( $item['receiverEmail'] ) ? sanitize_text_field( $item['receiverEmail'] ) : null;
        $yourReferFriend     = isset( $item['yourReferFriend'] ) ? intval( $item['yourReferFriend'] ) : null;
        $pointsExpirtionDate = isset( $item['pointsExpirtionDate'] ) ? sanitize_text_field( $item['pointsExpirtionDate'] ) : null;
        $pointsExpired       = isset( $item['pointsExpired'] ) ? intval( $item['pointsExpired'] ) : 0;
        $comments            = isset( $item['comments'] ) ? sanitize_text_field( $item['comments'] ) : null;

        // resolve customerId from email if not provided
        if ( $customerId <= 0 ) {
            $user = get_user_by( 'email', $customerEmail );
            if ( $user && isset( $user->ID ) ) {
                $customerId = intval( $user->ID );
            } else {
                $results[] = array( 'success' => false, 'error' => 'unknown_customer', 'message' => 'customerId not provided and no WP user found for customerEmail', 'index' => $idx );
                continue;
            }
        }

        // require appropriate points
        $is_positive = ( strtolower( $positive_negative ) === 'positive' );
        if ( $is_positive ) {
            if ( $pointsEarned <= 0 ) {
                $results[] = array( 'success' => false, 'error' => 'missing_points', 'message' => 'pointsEarned must be > 0 for positive events', 'index' => $idx );
                continue;
            }
        } else {
            if ( $pointsRedeemed <= 0 ) {
                $results[] = array( 'success' => false, 'error' => 'missing_points', 'message' => 'pointsRedeemed must be > 0 for negative events', 'index' => $idx );
                continue;
            }
        }

        // tables
        $t_event_details = $wpdb->prefix . 'NST_LR_cust_lty_event_details_table';
        $t_cust_pts      = $wpdb->prefix . 'NST_LR_Cust_lty_Pts_table';
        $t_events        = $wpdb->prefix . 'NST_LR_Lty_events_table';

        // idempotency check if transaction supplied
        // if ( $transaction_id ) {
        //     $exists_tx = $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$t_event_details} WHERE customer_id = %d AND transaction_id = %s", $customerId, $transaction_id ) );
        //     if ( intval( $exists_tx ) > 0 ) {
        //         $currentPoints = (float) $wpdb->get_var( $wpdb->prepare( "SELECT COALESCE(points_available,0) FROM {$t_cust_pts} WHERE customer_id = %d LIMIT 1", $customerId ) );
        //         $results[] = array( 'success' => true, 'message' => 'Event already processed (transaction exists).', 'currentPoints' => $currentPoints, 'transaction' => $transaction_id, 'index' => $idx );
        //         continue;
        //     }
        // }

        // lookup event name
        $event_name = null;
        if ( $eventid ) {
			// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- Safe: table name built from $wpdb->prefix
            $ev = $wpdb->get_row( $wpdb->prepare( "SELECT event_name FROM {$t_events} WHERE id = %d LIMIT 1", $eventid ) );
            if ( $ev ) $event_name = $ev->event_name;
        }
        if ( empty( $event_name ) && ! empty( $item['eventName'] ) ) $event_name = sanitize_text_field( $item['eventName'] );
        if ( empty( $event_name ) ) $event_name = 'External Event';

        // DB transaction per item
        $wpdb->query( 'START TRANSACTION' );
        try {
            // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- Safe: table name built from $wpdb->prefix
            $cust = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$t_cust_pts} WHERE customer_id = %d LIMIT 1", $customerId ), ARRAY_A );
            $old_earned   = $cust ? floatval( $cust['points_earned'] ) : 0.0;
            $old_redeemed = $cust ? floatval( $cust['points_redeemed'] ) : 0.0;
            $old_available = $cust ? floatval( $cust['points_available'] ) : max(0, $old_earned - $old_redeemed);

            if ( $is_positive ) {
                $addEarned = max(0.0, $pointsEarned);
                $deduct = 0.0;
            } else {
                $requested_deduct = max(0.0, $pointsRedeemed);
                $deduct = min( $requested_deduct, $old_available );
                $addEarned = 0.0;
            }

            $new_points_earned   = $old_earned + $addEarned;
            $new_points_redeemed = $old_redeemed + $deduct;
            $new_points_available = max( 0, $new_points_earned - $new_points_redeemed );

            // -----------------------------
            // CLIENT OVERRIDE: allow client to send pointsLeft / points_left
            // If present, override computed $new_points_available with client's value.
            // -----------------------------
            $client_points_left = null;
            if ( isset( $item['pointsLeft'] ) ) {
                $client_points_left = floatval( $item['pointsLeft'] );
            } elseif ( isset( $item['points_left'] ) ) {
                $client_points_left = floatval( $item['points_left'] );
            }

            if ( $client_points_left !== null ) {
                $new_points_available = max( 0, $client_points_left );
            }

            // write master
            if ( $cust ) {
                $upd = $wpdb->update( $t_cust_pts, array(
                    'points_earned'    => $new_points_earned,
                    'points_available' => $new_points_available,
                    'points_redeemed'  => $new_points_redeemed,
                    'updated_at'       => current_time( 'mysql' ),
                ), array( 'customer_id' => $customerId ), array( '%f','%f','%f','%s' ), array( '%d' ) );
                if ( $upd === false ) throw new Exception( 'Failed to update cust_pts: ' . $wpdb->last_error );
            } else {
                $ins = $wpdb->insert( $t_cust_pts, array(
                    'customer_id' => $customerId,
                    'points_earned' => $new_points_earned,
                    'points_available' => $new_points_available,
                    'points_redeemed' => $new_points_redeemed,
                    'created_at' => current_time( 'mysql' ),
                    'updated_at' => current_time( 'mysql' ),
                ), array( '%d','%f','%f','%f','%s','%s' ) );
                if ( $ins === false ) throw new Exception( 'Failed to insert cust_pts: ' . $wpdb->last_error );
            }

            // ledger insert (transaction_id may be NULL)
            $ledger_points_earned  = $is_positive ? $pointsEarned : 0.0;
            $ledger_points_redeemed = $is_positive ? $pointsRedeemed : $deduct;
            $now_sql  = current_time( 'mysql' );
            $now_date = gmdate( 'Y-m-d', current_time( 'timestamp' ) );

            $inserted = $wpdb->insert(
            $t_event_details,
            array(
                'customer_id'            => $customerId,
                'date_created'           => $now_date,
                'event_id'               => $eventid,
                'event_name'             => $event_name,
                'points_earned'          => $ledger_points_earned,
                'points_redeemed'        => $ledger_points_redeemed,
                'points_left'            => floatval( $new_points_available ),
                'transaction_id'         => $transaction_id,
                'amount'                 => $amount,
                'gift_code'              => $giftCode,
                'receiver_email'         => $receiverEmail,
                'refer_friend_id'        => $yourReferFriend ? intval( $yourReferFriend ) : null,
                'comments'               => $comments,
                'points_expiration_date' => $pointsExpirtionDate,
                'expired'                => $pointsExpired ? 1 : 0,
                'points_type'            => $is_positive ? 'positive' : 'negative',
                'created_at'             => $now_sql,
                'updated_at'             => $now_sql,
            ),
            array(
                '%d', // customer_id
                '%s', // date_created
                '%d', // event_id
                '%s', // event_name
                '%f', // points_earned
                '%f', // points_redeemed
                '%f', // points_left
                '%s', // transaction_id
                '%f', // amount
                '%s', // gift_code
                '%s', // receiver_email
                '%d', // refer_friend_id
                '%s', // comments
                '%s', // points_expiration_date
                '%d', // expired
                '%s', // points_type
                '%s', // created_at
                '%s', // updated_at
            )
        );

            if ( $inserted === false ) throw new Exception( 'Failed to insert event detail: ' . $wpdb->last_error );

            $wpdb->query( 'COMMIT' );
			// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- Safe: table name built from $wpdb->prefix
            $currentPoints = (float) $wpdb->get_var( $wpdb->prepare( "SELECT COALESCE(points_available,0) FROM {$t_cust_pts} WHERE customer_id = %d LIMIT 1", $customerId ) );

            $results[] = array( 'success' => true, 'message' => 'Event processed successfully.', 'currentPoints' => $currentPoints, 'transaction' => $transaction_id, 'index' => $idx );
        } catch ( Exception $e ) {
            $wpdb->query( 'ROLLBACK' );
            $results[] = array( 'success' => false, 'error' => 'db_error', 'message' => 'Failed to process event: ' . $e->getMessage(), 'index' => $idx );
        }
    } // end foreach items

    // if single item input, return single object for backward compatibility
    if ( count( $results ) === 1 && ! ( is_array( $body ) && array_keys( $body ) === range(0, count($body)-1) ) ) {
        return rest_ensure_response( $results[0] );
    }

    return rest_ensure_response( array( 'results' => $results ) );
}



   /**
 * GET - fetch events (single by transaction or by customerId or by customerEmail in JSON body)
 */
public function lrp_rest_get_event( WP_REST_Request $request ) {
    global $wpdb;

    // prefer JSON body for email (user requested email in JSON not URL)
    $body = $request->get_json_params();
    $params = $request->get_query_params();

    $t_event_details = $wpdb->prefix . 'NST_LR_cust_lty_event_details_table';
    $t_cust_pts      = $wpdb->prefix . 'NST_LR_Cust_lty_Pts_table';

    $customerId = isset( $params['customerId'] ) ? intval( $params['customerId'] ) : 0;
    $transaction = isset( $params['transaction'] ) ? sanitize_text_field( $params['transaction'] ) : '';
    $limit = isset( $params['limit'] ) ? max( 1, intval( $params['limit'] ) ) : 50;
    $offset = isset( $params['offset'] ) ? max( 0, intval( $params['offset'] ) ) : 0;

    // If email supplied in JSON body use it to resolve customerId
    if ( empty( $customerId ) && ! empty( $body ) && isset( $body['customerEmail'] ) ) {
        $email = sanitize_email( $body['customerEmail'] );
        if ( ! empty( $email ) ) {
            $user = get_user_by( 'email', $email );
            if ( $user && isset( $user->ID ) ) {
                $customerId = intval( $user->ID );
            } else {
                // No WP user found for email -> return empty result
                return rest_ensure_response( array( 'success' => true, 'customerId' => 0, 'currentPoints' => 0, 'events' => array(), 'message' => 'No customer found for provided email' ) );
            }
        }
    }

    // If transaction specified in query params, return single event
    if ( $transaction ) {
		// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- Safe: table name built from $wpdb->prefix
        $row = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$t_event_details} WHERE transaction_id = %s LIMIT 1", $transaction ), ARRAY_A );
        if ( ! $row ) return new WP_Error( 'not_found', 'Transaction not found', array( 'status' => 404 ) );

        // convert numeric fields
        $row['points_earned'] = floatval( $row['points_earned'] );
        $row['points_redeemed'] = floatval( $row['points_redeemed'] );
        $row['points_left'] = floatval( $row['points_left'] );

        // attach customer email (resolve from WP user if possible)
        $row['customer_email'] = '';
        if ( ! empty( $row['customer_id'] ) ) {
            $u = get_userdata( intval( $row['customer_id'] ) );
            if ( $u && isset( $u->user_email ) ) $row['customer_email'] = $u->user_email;
        }

        return rest_ensure_response( array( 'success' => true, 'event' => $row ) );
    }

    // If customerId (resolved from email or provided) -> return events for that customer
    if ( $customerId ) {
		// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- Safe: table name built from $wpdb->prefix
        $rows = $wpdb->get_results( $wpdb->prepare( "SELECT * FROM {$t_event_details} WHERE customer_id = %d ORDER BY id DESC LIMIT %d OFFSET %d", $customerId, $limit, $offset ), ARRAY_A );
		// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- Safe: table name built from $wpdb->prefix
        $currentPoints = (float) $wpdb->get_var( $wpdb->prepare( "SELECT COALESCE(points_available,0) FROM {$t_cust_pts} WHERE customer_id = %d LIMIT 1", $customerId ) );

        // resolve customer email once
        $customer_email = '';
        $u = get_userdata( $customerId );
        if ( $u && isset( $u->user_email ) ) $customer_email = $u->user_email;

        foreach ( $rows as &$r ) {
            $r['points_earned'] = isset( $r['points_earned'] ) ? floatval( $r['points_earned'] ) : 0.0;
            $r['points_redeemed'] = isset( $r['points_redeemed'] ) ? floatval( $r['points_redeemed'] ) : 0.0;
            $r['points_left'] = isset( $r['points_left'] ) ? floatval( $r['points_left'] ) : 0.0;
            // attach customer_email to each event row
            $r['customer_email'] = $customer_email;
        }
        return rest_ensure_response( array( 'success' => true, 'customerId' => $customerId, 'currentPoints' => $currentPoints, 'events' => $rows ) );
    }

    // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- Safe: table name built from $wpdb->prefix
    $rows = $wpdb->get_results( $wpdb->prepare( "SELECT * FROM {$t_event_details} ORDER BY id DESC LIMIT %d OFFSET %d", $limit, $offset ), ARRAY_A );
    foreach ( $rows as &$r ) {
        $r['points_earned'] = isset( $r['points_earned'] ) ? floatval( $r['points_earned'] ) : 0.0;
        $r['points_redeemed'] = isset( $r['points_redeemed'] ) ? floatval( $r['points_redeemed'] ) : 0.0;
        $r['points_left'] = isset( $r['points_left'] ) ? floatval( $r['points_left'] ) : 0.0;
        // attach customer_email (best-effort)
        $r['customer_email'] = '';
        if ( ! empty( $r['customer_id'] ) ) {
            $u = get_userdata( intval( $r['customer_id'] ) );
            if ( $u && isset( $u->user_email ) ) $r['customer_email'] = $u->user_email;
        }
    }
    return rest_ensure_response( array( 'success' => true, 'events' => $rows ) );
}


   /**
 * PUT - update existing event by transaction or id OR by (customerEmail + positive_negative) -> most recent matching event
 * Accepts single object or array of objects.
 */
public function lrp_rest_update_event( WP_REST_Request $request ) {
    global $wpdb;
    $body = $request->get_json_params();

    if ( empty( $body ) ) {
        return new WP_Error( 'invalid_payload', 'Invalid JSON payload', array( 'status' => 400 ) );
    }

    // Normalize to array of items (support single object or array)
    $items = is_array( $body ) && array_keys( $body ) === range(0, count($body)-1) ? $body : array( $body );

    $results = array();

    foreach ( $items as $idx => $item ) {
        if ( ! is_array( $item ) ) {
            $results[] = array( 'success' => false, 'error' => 'invalid_item', 'message' => 'Each item must be an object', 'index' => $idx );
            continue;
        }

        // --- Map common camelCase -> snake_case for convenience ---
        if ( isset( $item['pointsEarned'] ) && ! array_key_exists( 'points_earned', $item ) ) {
            $item['points_earned'] = $item['pointsEarned'];
        }
        if ( isset( $item['pointsRedeemed'] ) && ! array_key_exists( 'points_redeemed', $item ) ) {
            $item['points_redeemed'] = $item['pointsRedeemed'];
        }
        if ( isset( $item['eventDate'] ) && ! array_key_exists( 'date_created', $item ) ) {
            $item['date_created'] = $item['eventDate'];
        }
        if ( isset( $item['eventName'] ) && ! array_key_exists( 'event_name', $item ) ) {
            $item['event_name'] = $item['eventName'];
        }
        if ( isset( $item['giftCode'] ) && ! array_key_exists( 'gift_code', $item ) ) {
            $item['gift_code'] = $item['giftCode'];
        }
        if ( isset( $item['pointsExpirtionDate'] ) && ! array_key_exists( 'points_expiration_date', $item ) ) {
            $item['points_expiration_date'] = $item['pointsExpirtionDate'];
        }
        if ( isset( $item['eventid'] ) && ! array_key_exists( 'event_id', $item ) ) {
            $item['event_id'] = intval( $item['eventid'] );
        }
        if ( isset( $item['referFriend'] ) && ! array_key_exists( 'refer_friend_id', $item ) ) {
            $item['refer_friend_id'] = intval( $item['referFriend'] );
        }

        // sanitize a few immediate fields
        $transaction = isset( $item['transaction'] ) ? sanitize_text_field( $item['transaction'] ) : '';
        $event_id_db = isset( $item['id'] ) ? intval( $item['id'] ) : 0;
        $customerEmail = isset( $item['customerEmail'] ) ? sanitize_email( $item['customerEmail'] ) : '';
        $positive_negative = isset( $item['positive_negative'] ) ? sanitize_text_field( $item['positive_negative'] ) : '';

        // Make customerEmail required for ALL updates
        if ( empty( $customerEmail ) ) {
            $results[] = array( 'success' => false, 'error' => 'missing_customer_email', 'message' => 'customerEmail is required in JSON body for PUT', 'index' => $idx );
            continue;
        }

        // allowed updatable fields (DB keys)
        $allowed = array(
            'points_earned',
            'points_redeemed',
            'amount',
            'expired',
            'points_expiration_date',
            'comments',
            'refer_friend_id',
            'event_name',
            'date_created',
            'gift_code',
            'event_id'
        );

        $t_event_details = $wpdb->prefix . 'NST_LR_cust_lty_event_details_table';
        $t_cust_pts      = $wpdb->prefix . 'NST_LR_Cust_lty_Pts_table';

        // Determine the row to update
        if ( $transaction ) {
            $row = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$t_event_details} WHERE transaction_id = %s LIMIT 1", $transaction ), ARRAY_A );
            if ( ! $row ) {
                $results[] = array( 'success' => false, 'error' => 'not_found', 'message' => 'Event not found for provided transaction', 'index' => $idx );
                continue;
            }
            // verify that provided customerEmail matches event customer
            $u = get_userdata( intval( $row['customer_id'] ) );
            if ( ! $u || ! isset( $u->user_email ) || strtolower( $u->user_email ) !== strtolower( $customerEmail ) ) {
                $results[] = array( 'success' => false, 'error' => 'email_mismatch', 'message' => 'Provided customerEmail does not match event owner', 'index' => $idx );
                continue;
            }
        } elseif ( $event_id_db > 0 ) {
            $row = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$t_event_details} WHERE id = %d LIMIT 1", $event_id_db ), ARRAY_A );
            if ( ! $row ) {
                $results[] = array( 'success' => false, 'error' => 'not_found', 'message' => 'Event not found for provided id', 'index' => $idx );
                continue;
            }
            $u = get_userdata( intval( $row['customer_id'] ) );
            if ( ! $u || ! isset( $u->user_email ) || strtolower( $u->user_email ) !== strtolower( $customerEmail ) ) {
                $results[] = array( 'success' => false, 'error' => 'email_mismatch', 'message' => 'Provided customerEmail does not match event owner', 'index' => $idx );
                continue;
            }
        } else {
            // fallback: find customer by email and locate most recent event matching points_type
            $user = get_user_by( 'email', $customerEmail );
            if ( ! $user || ! isset( $user->ID ) ) {
                $results[] = array( 'success' => false, 'error' => 'unknown_customer', 'message' => 'No WP user found for provided customerEmail', 'index' => $idx );
                continue;
            }
            $cust_id = intval( $user->ID );
            if ( empty( $positive_negative ) ) {
                $results[] = array( 'success' => false, 'error' => 'missing_positive_negative', 'message' => 'positive_negative is required when transaction/id not provided', 'index' => $idx );
                continue;
            }
            $ptype = ( strtolower( $positive_negative ) === 'positive' ) ? 'positive' : 'negative';
            $row = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$t_event_details} WHERE customer_id = %d AND points_type = %s ORDER BY id DESC LIMIT 1", $cust_id, $ptype ), ARRAY_A );
            if ( ! $row ) {
                $results[] = array( 'success' => false, 'error' => 'not_found', 'message' => 'No matching event found for this customer with the specified positive_negative', 'index' => $idx );
                continue;
            }
            // ensure caller provided appropriate points field when using fallback
            if ( $ptype === 'positive' ) {
                if ( ! array_key_exists( 'points_earned', $item ) ) {
                    $results[] = array( 'success' => false, 'error' => 'missing_required_field', 'message' => 'points_earned (or pointsEarned) is required when updating a positive event via customerEmail + positive_negative', 'index' => $idx );
                    continue;
                }
            } else {
                if ( ! array_key_exists( 'points_redeemed', $item ) ) {
                    $results[] = array( 'success' => false, 'error' => 'missing_required_field', 'message' => 'points_redeemed (or pointsRedeemed) is required when updating a negative event via customerEmail + positive_negative', 'index' => $idx );
                    continue;
                }
            }
        }

        if ( ! $row ) {
            $results[] = array( 'success' => false, 'error' => 'not_found', 'message' => 'Event not found', 'index' => $idx );
            continue;
        }

        $customer_id = intval( $row['customer_id'] );

        // Build update_data from allowed fields; choose formats carefully
        $update_data = array();
        $update_formats = array();
        foreach ( $allowed as $f ) {
            if ( array_key_exists( $f, $item ) ) {
                // numeric floats
                if ( in_array( $f, array( 'points_earned','points_redeemed','amount' ) ) ) {
                    $update_data[$f] = floatval( $item[$f] );
                    $update_formats[] = '%f';
                }
                // integer fields
                elseif ( in_array( $f, array( 'expired','refer_friend_id','event_id' ) ) ) {
                    $update_data[$f] = intval( $item[$f] );
                    $update_formats[] = '%d';
                }
                // string/date fields
                else {
                    $update_data[$f] = sanitize_text_field( $item[$f] );
                    $update_formats[] = '%s';
                }
            }
        }

        if ( empty( $update_data ) ) {
            $results[] = array( 'success' => false, 'error' => 'nothing_to_update', 'message' => 'No updatable fields provided', 'index' => $idx );
            continue;
        }

        // Do the update inside a DB transaction
        $wpdb->query( 'START TRANSACTION' );
        try {
            $update_data['updated_at'] = current_time( 'mysql' );
            $update_formats[] = '%s';

            // choose where clause depending on how we found the row
            if ( ! empty( $transaction ) ) {
                $where = array( 'transaction_id' => $transaction );
                $where_format = array( '%s' );
            } elseif ( $event_id_db > 0 ) {
                $where = array( 'id' => $event_id_db );
                $where_format = array( '%d' );
            } else {
                $where = array( 'id' => intval( $row['id'] ) );
                $where_format = array( '%d' );
            }

            // optional debug: uncomment while testing
            // error_log('[lrp-debug] update where: ' . print_r($where, true) . ' update_data: ' . print_r($update_data, true));

            $res = $wpdb->update( $t_event_details, $update_data, $where, $update_formats, $where_format );
            if ( $res === false ) throw new Exception( 'Failed updating ledger: ' . $wpdb->last_error );

            // recompute master totals
            $sum_earned = (float) $wpdb->get_var( $wpdb->prepare( "SELECT COALESCE(SUM(points_earned),0) FROM {$t_event_details} WHERE customer_id = %d", $customer_id ) );
            $sum_redeemed = (float) $wpdb->get_var( $wpdb->prepare( "SELECT COALESCE(SUM(points_redeemed),0) FROM {$t_event_details} WHERE customer_id = %d", $customer_id ) );
            $new_available = max( 0, $sum_earned - $sum_redeemed );

            // -----------------------------
            // CLIENT OVERRIDE: allow client-supplied pointsLeft / points_left on update
            // If present in input item, override computed $new_available
            // -----------------------------
            $client_points_left = null;
            if ( isset( $item['pointsLeft'] ) ) {
                $client_points_left = floatval( $item['pointsLeft'] );
            } elseif ( isset( $item['points_left'] ) ) {
                $client_points_left = floatval( $item['points_left'] );
            }

            if ( $client_points_left !== null ) {
                $new_available = max( 0, $client_points_left );
            }

            $master_exists = $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$t_cust_pts} WHERE customer_id = %d", $customer_id ) );
            if ( intval( $master_exists ) > 0 ) {
                $upd = $wpdb->update( $t_cust_pts, array(
                    'points_earned' => $sum_earned,
                    'points_redeemed' => $sum_redeemed,
                    'points_available' => $new_available,
                    'updated_at' => current_time( 'mysql' )
                ), array( 'customer_id' => $customer_id ), array( '%f','%f','%f','%s' ), array( '%d' ) );
                if ( $upd === false ) throw new Exception( 'Failed updating master: ' . $wpdb->last_error );
            } else {
                $ins = $wpdb->insert( $t_cust_pts, array(
                    'customer_id' => $customer_id,
                    'points_earned' => $sum_earned,
                    'points_redeemed' => $sum_redeemed,
                    'points_available' => $new_available,
                    'created_at' => current_time( 'mysql' ),
                    'updated_at' => current_time( 'mysql' )
                ), array( '%d','%f','%f','%f','%s','%s' ) );
                if ( $ins === false ) throw new Exception( 'Failed inserting master: ' . $wpdb->last_error );
            }

            $wpdb->query( 'COMMIT' );

            $results[] = array(
                'success' => true,
                'message' => 'Event updated and master totals recomputed.',
                'customerId' => $customer_id,
                'pointsEarned' => $sum_earned,
                'pointsRedeemed' => $sum_redeemed,
                'pointsAvailable' => $new_available,
                'index' => $idx
            );
        } catch ( Exception $e ) {
            $wpdb->query( 'ROLLBACK' );
            error_log( '[lrp] lrp_rest_update_event error: ' . $e->getMessage() );
            $results[] = array( 'success' => false, 'error' => 'db_error', 'message' => 'Failed to update event: ' . $e->getMessage(), 'index' => $idx );
        }
    } // end foreach items

    // return single result for single input for backwards compatibility
    if ( count( $results ) === 1 && ! ( is_array( $body ) && array_keys( $body ) === range(0, count($body)-1) ) ) {
        return rest_ensure_response( $results[0] );
    }

    return rest_ensure_response( array( 'results' => $results ) );
}

    /**
     * Dev helper: register a tiny debug route so you can confirm the class is loaded
     * (optional; remove in production)
     */
    public function lrp_register_debug_route() {
        register_rest_route( 'lrp/v1', '/ping', [
            'methods' => 'GET',
            'callback' => function() { return rest_ensure_response( [ 'ok' => true, 'time' => current_time('mysql') ] ); },
            'permission_callback' => '__return_true',
        ] );
    }
}

new LRP_API_Endpoints();